server:
  port: 3000
MODE: 'normal'
MODELS_DIR: './**/*.model.js'
LOG_MODELS_DIR: './**/{alpha,log-message,log-group}.model.js'
db:
  dialect: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'test_user'
  password: 'password'
  database: 'nest_example'
  define:
    underscored: true
    paranoid: false
    timestamps: true
    freezeTableName: false
logsDB:
  dialect: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'atm_user'
  password: 'StrongP@ssw0rd'
  database: 'logs_db_dev'
  define:
    underscored: true
    paranoid: false
    timestamps: true
    freezeTableName: false
JWT:
  secretKey: 'secret_key'
S3:
  credentials:
    accessKeyId: 'AKIA4MOXDGQG6DTPIBMD'
    secretAccessKey: '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'
  bucket: 'mersal-media-dev'
twilio:
  appSid: ''
  authToken: ''
  messagingSeviceSid: ''
ses:
  credentials:
    region: 'eu-west-1'
    accessKeyId: 'AKIA4MOXDGQGWZPFXODL'
    secretAccessKey: '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'
  email:
    from: 'no-reply@mersalapp.ae'
    name: 'Altayer Motors'
firebase: ''
sentryDSN: ''
